server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka