server:
  port: 8761
spring:
  application:
    name: eureka-server
  cloud:
    compatibility-verifier:
      enabled: false
eureka:
  hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.hostname}:${server.port}/eureka/
